
    create table category (
       category_id bigint generated by default as identity,
        category_name varchar(255),
        primary key (category_id)
    );

    create table example (
       example_id bigint generated by default as identity,
        text varchar(255),
        expressionid bigint,
        primary key (example_id)
    );

    create table expression (
       expression_id bigint generated by default as identity,
        text varchar(255),
        translation varchar(255),
        category_id bigint,
        user_id bigint,
        primary key (expression_id)
    );

    create table expression_example_list (
       expression_expression_id bigint not null,
        example_list_example_id bigint not null
    );

    create table user (
       user_id bigint generated by default as identity,
        admin boolean not null,
        name varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (user_id)
    );

    alter table expression_example_list 
       add constraint UK_o6h7g87n6yske7w2tuthevcif unique (example_list_example_id);

    alter table user 
       add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);

    alter table example 
       add constraint FKooxtflhy1d8wvqhedyoyuj6x6 
       foreign key (expressionid) 
       references expression;

    alter table expression 
       add constraint FKsrn5i84chdp3afod6qky24py2 
       foreign key (category_id) 
       references category;

    alter table expression 
       add constraint FKj3ltm12g0jm4oji70uixrey6c 
       foreign key (user_id) 
       references user;

    alter table expression_example_list 
       add constraint FKla7uj87yk1vcprbdxrrke3v9c 
       foreign key (example_list_example_id) 
       references example;

    alter table expression_example_list 
       add constraint FK4vrro23nx19ap6o3n2ql68tvj 
       foreign key (expression_expression_id) 
       references expression;
